# Generated by Django 4.2.6 on 2023-10-30 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("house_name", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=50)),
                ("zip_code", models.IntegerField(default=0)),
                ("address", models.CharField(max_length=200)),
                ("unit", models.IntegerField(default=0)),
                ("floor", models.IntegerField(default=0)),
                ("bedrooms_count", models.IntegerField(default=0)),
                ("bathrooms_count", models.IntegerField(default=0)),
                ("rent_cost", models.IntegerField(default=0)),
                ("size", models.IntegerField(default=0)),
                ("initial_fee", models.IntegerField(default=0)),
                ("availability", models.BooleanField(default=True)),
                ("photo", models.ImageField(upload_to="img/houses")),
                ("description", models.TextField(blank=True)),
                ("date_posted", models.DateTimeField(auto_now_add=True)),
                ("rating", models.FloatField(default=0.0)),
                ("is_verified", models.BooleanField(default=False)),
                ("finding_rm", models.BooleanField(default=True)),
                ("poster", models.CharField(max_length=50)),
                ("wished", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Comments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("poster", models.CharField(max_length=50)),
                ("international_friendly", models.BooleanField(default=True)),
                ("content", models.TextField(blank=True)),
                ("rating", models.IntegerField(default=0)),
                ("finding_rm", models.BooleanField(default=False)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="nova.property",
                    ),
                ),
            ],
        ),
    ]
