# Generated by Django 4.2.6 on 2023-10-30 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nova", "0002_remove_property_house_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="property",
            old_name="title",
            new_name="house_name",
        ),
        migrations.AlterField(
            model_name="property",
            name="photo",
            field=models.ImageField(upload_to="img/houses/"),
        ),
    ]
