# Generated by Django 4.2.6 on 2023-10-30 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nova", "0003_rename_title_property_house_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="content",
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name="property",
            name="description",
            field=models.TextField(max_length=2000),
        ),
    ]
