# Generated by Django 4.2.6 on 2023-10-30 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nova", "0004_alter_comments_content_alter_property_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="photo",
            field=models.ImageField(upload_to="houses/"),
        ),
    ]
