# Generated by Django 4.2.6 on 2023-10-30 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nova", "0005_alter_property_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="finding_rm",
            field=models.IntegerField(default=0),
        ),
    ]
