# Generated by Django 4.2.6 on 2023-11-02 20:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nova", "0006_alter_property_finding_rm"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="wished",
        ),
    ]
