# Generated by Django 4.2.6 on 2023-11-18 00:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("nova", "0008_property_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="rating",
        ),
        migrations.AddField(
            model_name="comments",
            name="user",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
