# Generated by Django 4.2.6 on 2023-11-18 03:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("nova", "0009_remove_property_rating_comments_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="date_posted",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
