# Generated by Django 4.2.6 on 2023-11-19 04:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("actions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="deleted_house_name",
            field=models.CharField(default="", max_length=100),
        ),
    ]
